//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedUsers
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public System.DateTime BlockTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
